name: Watch File Commits

on:
  push:
    paths:
      - 'test.txt'

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Embed
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          TITLE=$(git log -1 --pretty=%s)
          DESCRIPTION=$(git log -1 --pretty=%b)
          DESCRIPTION=${DESCRIPTION:-"No description"}

          curl -X POST "$DISCORD_WEBHOOK" \
          -H "Content-Type: application/json" \
          -d "$(jq -n --arg title "$TITLE" --arg description "$DESCRIPTION" '{
            embeds: [{
              title: $title,
              description: $description,
              color: 65280
            }]
          }')"
